export const data = {
  module_name: ['acl'],
  module_desp: ['permission management'],
  case_groups_data: {
    get_group_list: {
      data: {
        id: 17630,
        title: 'get_group_list',
        desp: 'get a list of permission groups',
        Auditor__username: 'GL',
        audit_time: '2024-11-19T17:55:19',
        create_time: '2024-11-19T17:55:19',
        creater__username: 'GL',
        audiVerify__name: '已审核',
        caseType__name: 'API测试类',
        caseID_api__audit: true,
      },
      in_example: '{"jsonrpc":"2.0","id":1,"method":"call","params":["","acl","get_group_list"]}',
      out_example: '{"jsonrpc": "2.0", "id": 1, "result": { "groups": ["root", "test"] }}',
      module_name: ['acl'],
      params: [],
      results: [
        {
          id: 745998,
          keyName: 'groups',
          keyValue: null,
          desp: 'list of permission groups',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'array',
          caseID_id: 17630,
        },
      ],
    },
    add_group: {
      data: {
        id: 17631,
        title: 'add_group',
        desp: 'add permission group',
        Auditor__username: 'GL',
        audit_time: '2024-11-19T17:55:19',
        create_time: '2024-11-19T17:55:19',
        creater__username: 'GL',
        audiVerify__name: '已审核',
        caseType__name: 'API测试类',
        caseID_api__audit: true,
      },
      in_example:
        '{"jsonrpc":"2.0","id":1,"method":"call","params":["","acl","add_group", {"group": "test"}]}',
      out_example: '{"id":1,"jsonrpc":"2.0","result":[]}',
      module_name: ['acl'],
      params: [
        {
          id: 348255,
          keyName: 'group',
          keyValue: null,
          desp: 'permission group',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17631,
        },
      ],
      results: [
        {
          id: 745999,
          keyName: '?err_code',
          keyValue: null,
          desp: 'error code [-1: group already exists]',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'number',
          caseID_id: 17631,
        },
        {
          id: 746000,
          keyName: '?err_msg',
          keyValue: null,
          desp: 'error message ["exists"]',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17631,
        },
      ],
    },
    remove_group: {
      data: {
        id: 17632,
        title: 'remove_group',
        desp: 'remove permission group',
        Auditor__username: 'GL',
        audit_time: '2024-11-19T17:55:19',
        create_time: '2024-11-19T17:55:19',
        creater__username: 'GL',
        audiVerify__name: '已审核',
        caseType__name: 'API测试类',
        caseID_api__audit: true,
      },
      in_example:
        '{"jsonrpc":"2.0","id":1,"method":"call","params":["","acl","remove_group", {"group": "test"}]}',
      out_example: '{"id":1,"jsonrpc":"2.0","result":[]}',
      module_name: ['acl'],
      params: [
        {
          id: 348256,
          keyName: 'group',
          keyValue: null,
          desp: 'permission group',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17632,
        },
      ],
      results: [
        {
          id: 746001,
          keyName: '?err_code',
          keyValue: null,
          desp: 'error code [-1: group does not exist]',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'number',
          caseID_id: 17632,
        },
      ],
    },
    get_acl_list: {
      data: {
        id: 17633,
        title: 'get_acl_list',
        desp: 'get all permissions for a group',
        Auditor__username: 'GL',
        audit_time: '2024-11-19T17:55:19',
        create_time: '2024-11-19T17:55:19',
        creater__username: 'GL',
        audiVerify__name: '已审核',
        caseType__name: 'API测试类',
        caseID_api__audit: true,
      },
      in_example:
        '{"jsonrpc":"2.0","id":1,"method":"call","params":["","acl","get_acl_list", {"group": "test"}]}',
      out_example: '{"id":1,"jsonrpc":"2.0","result":{"acls":[]}}',
      module_name: ['acl'],
      params: [
        {
          id: 348257,
          keyName: 'group',
          keyValue: null,
          desp: 'permission group',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17633,
        },
      ],
      results: [
        {
          id: 746002,
          keyName: 'acls',
          keyValue: null,
          desp: 'permission list',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'array',
          caseID_id: 17633,
        },
        {
          id: 746003,
          keyName: '?acls.scope',
          keyValue: null,
          desp: 'scope of permission',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17633,
        },
        {
          id: 746004,
          keyName: '?acls.entry',
          keyValue: null,
          desp: 'permission entry',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17633,
        },
        {
          id: 746005,
          keyName: '?acls.perm',
          keyValue: null,
          desp: 'permission',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17633,
        },
      ],
    },
    add_acl: {
      data: {
        id: 17634,
        title: 'add_acl',
        desp: 'add permission',
        Auditor__username: 'GL',
        audit_time: '2024-11-19T17:55:19',
        create_time: '2024-11-19T17:55:19',
        creater__username: 'GL',
        audiVerify__name: '已审核',
        caseType__name: 'API测试类',
        caseID_api__audit: true,
      },
      in_example:
        '{"jsonrpc":"2.0","id":1,"method":"call","params":["","acl","add_acl", {"group": "test", "scope": "rpc", "entry": "system.info", "perm": "x"}]}',
      out_example: '{"id":1,"jsonrpc":"2.0","result":{"err_msg":"exists","err_code":-1}}',
      module_name: ['acl'],
      params: [
        {
          id: 348258,
          keyName: 'group',
          keyValue: null,
          desp: 'permission group',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17634,
        },
        {
          id: 348259,
          keyName: 'scope',
          keyValue: null,
          desp: 'scope of permission',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17634,
        },
        {
          id: 348260,
          keyName: 'entry',
          keyValue: null,
          desp: 'permission entry',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17634,
        },
        {
          id: 348261,
          keyName: 'perm',
          keyValue: null,
          desp: 'permission',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17634,
        },
      ],
      results: [
        {
          id: 746006,
          keyName: '?err_code',
          keyValue: null,
          desp: 'error code [-1: permission already exists]',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'number',
          caseID_id: 17634,
        },
        {
          id: 746007,
          keyName: '?err_msg',
          keyValue: null,
          desp: 'error message',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17634,
        },
      ],
    },
    remove_acl: {
      data: {
        id: 17635,
        title: 'remove_acl',
        desp: 'remove permission',
        Auditor__username: 'GL',
        audit_time: '2024-11-19T17:55:19',
        create_time: '2024-11-19T17:55:19',
        creater__username: 'GL',
        audiVerify__name: '已审核',
        caseType__name: 'API测试类',
        caseID_api__audit: true,
      },
      in_example:
        '{"jsonrpc":"2.0","id":1,"method":"call","params":["","acl","remove_acl", {"group": "test", "scope": "rpc", "entry": "system.info"}]}',
      out_example: '{"id":1,"jsonrpc":"2.0","result":{"err_msg":"not exists","err_code":-1}}',
      module_name: ['acl'],
      params: [
        {
          id: 348262,
          keyName: 'group',
          keyValue: null,
          desp: 'permission group',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17635,
        },
        {
          id: 348263,
          keyName: 'scope',
          keyValue: null,
          desp: 'scope of permission',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17635,
        },
        {
          id: 348264,
          keyName: 'entry',
          keyValue: null,
          desp: 'permission entry',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17635,
        },
      ],
      results: [
        {
          id: 746008,
          keyName: '?err_code',
          keyValue: null,
          desp: 'error code [-1: permission already exists]',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'number',
          caseID_id: 17635,
        },
        {
          id: 746009,
          keyName: '?err_msg',
          keyValue: null,
          desp: 'error message',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17635,
        },
      ],
    },
    add_user: {
      data: {
        id: 17636,
        title: 'add_user',
        desp: 'add a user to a permission group',
        Auditor__username: 'GL',
        audit_time: '2024-11-19T17:55:19',
        create_time: '2024-11-19T17:55:19',
        creater__username: 'GL',
        audiVerify__name: '已审核',
        caseType__name: 'API测试类',
        caseID_api__audit: true,
      },
      in_example:
        '{"jsonrpc":"2.0","id":1,"method":"call","params":["","acl","add_user", {"group": "test", "username": "test"}]}',
      out_example: '{"id":1,"jsonrpc":"2.0","result":[]}',
      module_name: ['acl'],
      params: [
        {
          id: 348265,
          keyName: 'group',
          keyValue: null,
          desp: 'permission group',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17636,
        },
        {
          id: 348266,
          keyName: 'username',
          keyValue: null,
          desp: 'username',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17636,
        },
      ],
      results: [],
    },
    remove_user: {
      data: {
        id: 17637,
        title: 'remove_user',
        desp: 'remove user',
        Auditor__username: 'GL',
        audit_time: '2024-11-19T17:55:19',
        create_time: '2024-11-19T17:55:19',
        creater__username: 'GL',
        audiVerify__name: '已审核',
        caseType__name: 'API测试类',
        caseID_api__audit: true,
      },
      in_example:
        '{"jsonrpc":"2.0","id":1,"method":"call","params":["","acl","remove_user", {"group": "test", "username": "test"}]}',
      out_example: '{"id":1,"jsonrpc":"2.0","result":{"err_msg":"not exists","err_code":-1}}',
      module_name: ['acl'],
      params: [
        {
          id: 348267,
          keyName: 'username',
          keyValue: null,
          desp: 'username',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17637,
        },
      ],
      results: [
        {
          id: 746010,
          keyName: 'err_code',
          keyValue: null,
          desp: 'error code [-1: the user does not exist]',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'number',
          caseID_id: 17637,
        },
        {
          id: 746011,
          keyName: 'err_msg',
          keyValue: null,
          desp: 'error message',
          status: true,
          caseUse__use: '功能测试',
          dataType__name: 'string',
          caseID_id: 17637,
        },
      ],
    },
  },
};
